apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.10.30:6443
  name: 10.0.10.30
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.17.0.1:6443
  name: 172.17.0.1
contexts:
- context:
    cluster: 10.0.10.30
    user: wcp:10.0.10.30:administrator@vsphere.local
  name: 10.0.10.30
- context:
    cluster: 172.17.0.1
    namespace: demo
    user: wcp:172.17.0.1:administrator@vsphere.local
  name: demo
current-context: demo
kind: Config
preferences: {}
users:
- name: wcp:10.0.10.30:administrator@vsphere.local
  user:
    token: eyJraWQiOiIyMDgxOEMxRTIwNzcwRDY4RDdCMzdDREIxQTRCRjlCNjYxRUFGNjAyIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJBZG1pbmlzdHJhdG9yQHZzcGhlcmUubG9jYWwiLCJhdWQiOiJ2bXdhcmUtdGVzOnZjOnZuczprOHMiLCJkb21haW4iOiJ2c3BoZXJlLmxvY2FsIiwiaXNzIjoiaHR0cHM6XC9cLzEwLjAuMTAuMTBcL29wZW5pZGNvbm5lY3RcL3ZzcGhlcmUubG9jYWwiLCJncm91cF9uYW1lcyI6WyJMaWNlbnNlU2VydmljZS5BZG1pbmlzdHJhdG9yc0B2c3BoZXJlLmxvY2FsIiwiU3lzdGVtQ29uZmlndXJhdGlvbi5SZWFkT25seUB2c3BoZXJlLmxvY2FsIiwiU3lzdGVtQ29uZmlndXJhdGlvbi5TdXBwb3J0VXNlcnNAdnNwaGVyZS5sb2NhbCIsIkFkbWluaXN0cmF0b3JzQHZzcGhlcmUubG9jYWwiLCJFdmVyeW9uZUB2c3BoZXJlLmxvY2FsIiwiQ0FBZG1pbnNAdnNwaGVyZS5sb2NhbCIsIlN5c3RlbUNvbmZpZ3VyYXRpb24uQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIlN5c3RlbUNvbmZpZ3VyYXRpb24uQmFzaFNoZWxsQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIlVzZXJzQHZzcGhlcmUubG9jYWwiXSwiZXhwIjoxNjIyNzQwNTA2LCJpYXQiOjE2MjI3MDQ1MDYsImp0aSI6IjkzMDY0YmNkLTliMWQtNGYxMi05OTRlLTJjYmZlNmE4MWVkYyIsInVzZXJuYW1lIjoiQWRtaW5pc3RyYXRvciJ9.V4hrKiKjRUQPpzqFiXPEIXy0HwwHq8OzzBxCN_qSERWW0-hL_GysY_dPDy-QBbjkb39Ythy-bvklzKK6fXW03U7bOTBOPFz2R1_wn3-r39HTPhi5XF0v3mECRI5qOScsR1_5kZ7myJ71-0CHFKNhpXGk1S1L2ZOO0ytORnULbQkQWTO7eDMteMKnjH7z3vgJCydj0h_pwyUkXQGX1N7Hl22-V4QQVwxNjIk5_w1L2KmChENbsYV68OzxKHprP0Q9R5Q_injGOzQhClHNDw-dHakKsKrYfZquNRJX_ZuQt_a6WKXyvG0xQY4Bc79Zh2EzUItBEqgxpHHzgU8NDKw4TA
- name: wcp:172.17.0.1:administrator@vsphere.local
  user:
    token: eyJraWQiOiIyMDgxOEMxRTIwNzcwRDY4RDdCMzdDREIxQTRCRjlCNjYxRUFGNjAyIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJBZG1pbmlzdHJhdG9yQHZzcGhlcmUubG9jYWwiLCJhdWQiOiJ2bXdhcmUtdGVzOnZjOnZuczprOHMiLCJkb21haW4iOiJ2c3BoZXJlLmxvY2FsIiwiaXNzIjoiaHR0cHM6XC9cLzEwLjAuMTAuMTBcL29wZW5pZGNvbm5lY3RcL3ZzcGhlcmUubG9jYWwiLCJncm91cF9uYW1lcyI6WyJMaWNlbnNlU2VydmljZS5BZG1pbmlzdHJhdG9yc0B2c3BoZXJlLmxvY2FsIiwiU3lzdGVtQ29uZmlndXJhdGlvbi5SZWFkT25seUB2c3BoZXJlLmxvY2FsIiwiU3lzdGVtQ29uZmlndXJhdGlvbi5TdXBwb3J0VXNlcnNAdnNwaGVyZS5sb2NhbCIsIkFkbWluaXN0cmF0b3JzQHZzcGhlcmUubG9jYWwiLCJFdmVyeW9uZUB2c3BoZXJlLmxvY2FsIiwiQ0FBZG1pbnNAdnNwaGVyZS5sb2NhbCIsIlN5c3RlbUNvbmZpZ3VyYXRpb24uQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIlN5c3RlbUNvbmZpZ3VyYXRpb24uQmFzaFNoZWxsQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIlVzZXJzQHZzcGhlcmUubG9jYWwiXSwiZXhwIjoxNjIyNzQwNTA3LCJpYXQiOjE2MjI3MDQ1MDcsImp0aSI6Ijg2ZGYxMzcyLTY1NGMtNGRiNy04Mzk1LTJkZjViOTgzYTIyYiIsInVzZXJuYW1lIjoiQWRtaW5pc3RyYXRvciJ9.ONXKIqazJcbERC9fcuZmDuMO6tJs7yb--cLBWoBDNbzSOClb1DCXS1HFKzBxPutzZrI_dDoaT_6VSAgjk6zV2MDfIzMu5YQ-oyjvf-fsXAnKsAo9m83uSg2e7K7CyYnE5Hhorg0NYnpUKy28yu-VYyRWr3Y9PInUClNFshQWH5oInKrP7ugftobREsNxiPUITleWqedY5HQRgf_kCd8cDS_2G1KXPiborCzIj85Z_MnCXM-xJLGlVZ5DRdStDjfYGgsYIARGARoKaiGbUghG7LK1Bh8rqmQFNQv1ku6KVQEzn5KwLlGWPIdBhGCDuo6D4B1HTO4f23aZTCYbdMRc3Q
