apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.10.30:6443
  name: 10.0.10.30
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.17.0.1:6443
  name: 172.17.0.1
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5ekNDQWJPZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EWXdOREUxTkRrek5Wb1hEVE14TURZd01qRTFOVFF6TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT3ZQCnhtblNpQndMMlROMGVzblFYZCtPc2xpU0Y1L0ZYdTk5WEJVRkFDNm1ucUUvSThsOUJxVXppb3FOdng2T2YycGMKcWc2K1pWVVZtQ0M1aWFUWTltc2dweDlZMnozZXlNMjRveUI3Wng3MUh6Umt3SzFocUlIK2o4VktQMmR1Z2l5VQpoRnhkWWUvUXYrblJUT0pqbnJJWDdaZno5WHpNcHkrc2hDMjZLQWYzSjVlK3dzYkxhdHBOZ2NFbWJML1hMZy9HCm1JVjNScFRmMmZsd2JwNlVOejEwQ3FESkNIUXdSV1NLSXRJZU5nNFBnekFvQzNISWdnV1MwM0xRK29Mcm5hLzQKd290Wi96TTl6d1pyWWc2SE5yRTFadTBTdFFvbndvRHZVN1FEUkdmclA5elRYcExCbGlXcjk2a09TZFZkbzNLcgpKL0tLZ2FoSUkzN1lHSENQZFFFQ0F3RUFBYU1tTUNRd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTFNGb0V3aGZWR2sraVFEdEVPVGVVRlMKcW9mRW9kckZVY3R0QSs1OHJwL1cvZzRSQlVSM2R3RmljekovcmI4S1NqNmh1Z25KN1dPaUJaaWVEeVBjVUx5cAp2RjNVcmxIV3FTWmJnSGRabzhKY0pRTll2ajhrT0dpUko3dGIvOGMvekxuVlFPbUJXYksxeWNnaWErZnlhTkdGClEvRFlvbHNTRENHUkhrUGIwQk1XbGExUGxpWTJiM2szY1RBZFpTOCszM2svWkdrSUhLeHVlUnZmcmxwMGFPSjUKRzBhMHBzNFV3YUcyM2xkQnMwMXFTbEFTQmsydXJ3VENIcE5rREUxZGFrUjJKcVVnWm9JcXZYQWM5Tm1HQXE1eAovWTlaQUNGQkl6MGkyQWYxTktwVHJ1TmdZMlU4dkFPVGhINDRVQ1p3a2F4V1d4NFlnelp2VzNLZzdTaFZ6SkE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://172.17.0.2:6443
  name: 172.17.0.2
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.10.30:6443
  name: supervisor-10.0.10.30
contexts:
- context:
    cluster: 10.0.10.30
    user: wcp:10.0.10.30:demo@vsphere.local
  name: 10.0.10.30
- context:
    cluster: 172.17.0.1
    namespace: demo
    user: wcp:172.17.0.1:demo@vsphere.local
  name: demo
- context:
    cluster: 172.17.0.2
    user: wcp:172.17.0.2:demo@vsphere.local
  name: demo-cluster
- context:
    cluster: 172.17.0.1
    namespace: demo2
    user: wcp:172.17.0.1:demo@vsphere.local
  name: demo2
- context:
    cluster: 172.17.0.1
    namespace: demo3
    user: wcp:172.17.0.1:demo@vsphere.local
  name: demo3
current-context: demo-cluster
kind: Config
preferences: {}
users:
- name: wcp:10.0.10.30:demo@vsphere.local
  user:
    token: eyJraWQiOiIyMDgxOEMxRTIwNzcwRDY4RDdCMzdDREIxQTRCRjlCNjYxRUFGNjAyIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkZW1vQHZzcGhlcmUubG9jYWwiLCJhdWQiOiJ2bXdhcmUtdGVzOnZjOnZuczprOHMiLCJkb21haW4iOiJ2c3BoZXJlLmxvY2FsIiwiaXNzIjoiaHR0cHM6XC9cLzEwLjAuMTAuMTBcL29wZW5pZGNvbm5lY3RcL3ZzcGhlcmUubG9jYWwiLCJncm91cF9uYW1lcyI6WyJMaWNlbnNlU2VydmljZS5BZG1pbmlzdHJhdG9yc0B2c3BoZXJlLmxvY2FsIiwiQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIkV2ZXJ5b25lQHZzcGhlcmUubG9jYWwiLCJTeXN0ZW1Db25maWd1cmF0aW9uLkFkbWluaXN0cmF0b3JzQHZzcGhlcmUubG9jYWwiXSwiZXhwIjoxNjI0NDc1NzQwLCJpYXQiOjE2MjQ0Mzk3NDAsImp0aSI6IjBjOTA5ZDAzLTI1YjQtNGM3Yi05MDQ5LWE4ZWUzZjcxNThkYyIsInVzZXJuYW1lIjoiZGVtbyJ9.SNBLan_pzmlQztlqrIoroyxzsaCTWpf7PlzsLER85mWZqvcSicxZ6k-j6zL5InJ9iY73UdaBCL8BLoktfLPqE4SXHe5BJtWpVKn2NcaIW42ZkufG7e3nhCpt7s00TMogxe-eRgfiSxVfPMvdAv6hyVDEW_9xm6K6r7xalHF-LO_Pt5agBWr9OX6V2QWD-etsgLJvyThFSFplkqFERbzP6OyDoVnSD2rAokBEOjPzBl1fhv_VjnKoetL88VG8vGmC-yYKTO1DDFIl22umbVS3VhP-0ptGCpzNmbbxBCdxqJLVOAZnO2XgCd_l8ej19KwhPVcwhc5ceEqWuOVEb2pjjQ
- name: wcp:172.17.0.1:demo@vsphere.local
  user:
    token: eyJraWQiOiIyMDgxOEMxRTIwNzcwRDY4RDdCMzdDREIxQTRCRjlCNjYxRUFGNjAyIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkZW1vQHZzcGhlcmUubG9jYWwiLCJhdWQiOiJ2bXdhcmUtdGVzOnZjOnZuczprOHMiLCJkb21haW4iOiJ2c3BoZXJlLmxvY2FsIiwiaXNzIjoiaHR0cHM6XC9cLzEwLjAuMTAuMTBcL29wZW5pZGNvbm5lY3RcL3ZzcGhlcmUubG9jYWwiLCJncm91cF9uYW1lcyI6WyJMaWNlbnNlU2VydmljZS5BZG1pbmlzdHJhdG9yc0B2c3BoZXJlLmxvY2FsIiwiQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIkV2ZXJ5b25lQHZzcGhlcmUubG9jYWwiLCJTeXN0ZW1Db25maWd1cmF0aW9uLkFkbWluaXN0cmF0b3JzQHZzcGhlcmUubG9jYWwiXSwiZXhwIjoxNjI0NDc1NzQzLCJpYXQiOjE2MjQ0Mzk3NDMsImp0aSI6IjEzNjM4ZDVmLWVkZWItNDgzZS1hNzBmLTgxNDkyNjhmZmQwOSIsInVzZXJuYW1lIjoiZGVtbyJ9.GVtfUsy2fvlRhJb7JJcXvBwxawd7weiEG2PK96WAxDGNdzZ5qtSPGLs-VlQddxjX32_mBYOstIBxAwAD7LCp4X9FEgafWnefePv26Bfqd2Ye2aO4hp9Xd-smNqrcjXvN84WRU0tDfad6s5ZzyUSZxcSdm0dHFNSWMJiFw_Fll_4ZNfIo_tg_lAxl9V1MjSSZ7vmy_U-xSt7z_chXRmBkvPAoe4XXUIiIiHMrE6_k07Gqib2OIFg9slAKPwRytyNO4VEBrrcNrihfEgcDQSgy25ApUhHz7chBZv50H6gZA3qLB_7dQYTjmzc6lB-JfX4q8lZUlkpaGXzK37Om9sIIQA
- name: wcp:172.17.0.2:demo@vsphere.local
  user:
    token: eyJraWQiOiIyMDgxOEMxRTIwNzcwRDY4RDdCMzdDREIxQTRCRjlCNjYxRUFGNjAyIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkZW1vQHZzcGhlcmUubG9jYWwiLCJhdWQiOiJ2bXdhcmUtdGVzOnZjOnZuczprOHM6OWFlYmJlZjQtYzEzOS00OTFhLWIwODYtMmQ2NTFhMDRhNTU3IiwiZG9tYWluIjoidnNwaGVyZS5sb2NhbCIsImlzcyI6Imh0dHBzOlwvXC8xMC4wLjEwLjEwXC9vcGVuaWRjb25uZWN0XC92c3BoZXJlLmxvY2FsIiwiZ3JvdXBfbmFtZXMiOlsiTGljZW5zZVNlcnZpY2UuQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIkFkbWluaXN0cmF0b3JzQHZzcGhlcmUubG9jYWwiLCJFdmVyeW9uZUB2c3BoZXJlLmxvY2FsIiwiU3lzdGVtQ29uZmlndXJhdGlvbi5BZG1pbmlzdHJhdG9yc0B2c3BoZXJlLmxvY2FsIl0sImV4cCI6MTYyNDQ3NTc0MiwiaWF0IjoxNjI0NDM5NzQyLCJqdGkiOiJlYWI4YjVkOS0yMmMzLTQ2NmQtYTBlZS1lNmNiZDUwZjJlMjQiLCJ1c2VybmFtZSI6ImRlbW8ifQ.fxSbxftC-Pb81eB8uAuRkgntvDn20wpXfJPy1kTCvQrcctxkejkbXx0UZ2yQpgTvFLa-EMQyZntsEnvkI8bFweJF2dG4RD6ly6CkJs8G2Cqvn5-gbTSjUbb2qQogHyaMsCVQC0cUeW_5gr0apCNmxYxeCbEd7ONF0ERgTo3YHE_pEkiGOPqzpmLV1uLBIj6XLpi6u3YaDTnRaanUR3CzUD8dh4c10EKH0eBcwaKtndn3qyvs7mPRWIyk9-0mP1wBMZFU1PALDcQ6rLkQEzU85zsCOiHLDwf2slSsXaoPIGzJBGDbGA8hOAbPdZfrRAUiNSaJ-MTXIwZgCtUOtz1bgw
