apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.10.30:6443
  name: 10.0.10.30
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.17.0.1:6443
  name: 172.17.0.1
contexts:
- context:
    cluster: 10.0.10.30
    user: wcp:10.0.10.30:demo@vsphere.local
  name: 10.0.10.30
- context:
    cluster: 172.17.0.1
    namespace: demo
    user: wcp:172.17.0.1:demo@vsphere.local
  name: demo
- context:
    cluster: 172.17.0.1
    namespace: demo2
    user: wcp:172.17.0.1:demo@vsphere.local
  name: demo2
current-context: 10.0.10.30
kind: Config
preferences: {}
users:
- name: wcp:10.0.10.30:demo@vsphere.local
  user:
    token: eyJraWQiOiIyMDgxOEMxRTIwNzcwRDY4RDdCMzdDREIxQTRCRjlCNjYxRUFGNjAyIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkZW1vQHZzcGhlcmUubG9jYWwiLCJhdWQiOiJ2bXdhcmUtdGVzOnZjOnZuczprOHMiLCJkb21haW4iOiJ2c3BoZXJlLmxvY2FsIiwiaXNzIjoiaHR0cHM6XC9cLzEwLjAuMTAuMTBcL29wZW5pZGNvbm5lY3RcL3ZzcGhlcmUubG9jYWwiLCJncm91cF9uYW1lcyI6WyJMaWNlbnNlU2VydmljZS5BZG1pbmlzdHJhdG9yc0B2c3BoZXJlLmxvY2FsIiwiQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIkV2ZXJ5b25lQHZzcGhlcmUubG9jYWwiLCJTeXN0ZW1Db25maWd1cmF0aW9uLkFkbWluaXN0cmF0b3JzQHZzcGhlcmUubG9jYWwiXSwiZXhwIjoxNjIzNjk2ODMxLCJpYXQiOjE2MjM2NjA4MzEsImp0aSI6ImE2OWIwZTU1LTYwYWEtNDI5Ni1hNTYzLTI3ZTVlNjA3Zjc1NiIsInVzZXJuYW1lIjoiZGVtbyJ9.Nz5mlIPLeNale-jz7MICqb53XhlLAppj8zH304A_0EuNZJWkTQmMB46aK5ittae3IOp_D9G0CcYMvQY2FrUvFC6189x7gXJCTz_tRprq_9iuMPFmQDM8PvZTtEIE2PNhDS3OjE0y3dQCUSl4ejoHUEfS1rnIgMzUdU-rZVWocSclahAC6pKWHbdqGe5MVAgnwE5Q8Cvg422vEtRmCtIVplZiLg-fe4KfURH2MLzhjbFiHsgkgribGvdaB0i-qLlVdmis8OwsM4Sy2tzs0OIdp2sHASOf3BM7-RLyh3xPMY8lwmJ5Utjp37mN6FjUtNd_Bge5--vO42uzlg-nWW4h1Q
- name: wcp:172.17.0.1:demo@vsphere.local
  user:
    token: eyJraWQiOiIyMDgxOEMxRTIwNzcwRDY4RDdCMzdDREIxQTRCRjlCNjYxRUFGNjAyIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkZW1vQHZzcGhlcmUubG9jYWwiLCJhdWQiOiJ2bXdhcmUtdGVzOnZjOnZuczprOHMiLCJkb21haW4iOiJ2c3BoZXJlLmxvY2FsIiwiaXNzIjoiaHR0cHM6XC9cLzEwLjAuMTAuMTBcL29wZW5pZGNvbm5lY3RcL3ZzcGhlcmUubG9jYWwiLCJncm91cF9uYW1lcyI6WyJMaWNlbnNlU2VydmljZS5BZG1pbmlzdHJhdG9yc0B2c3BoZXJlLmxvY2FsIiwiQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIkV2ZXJ5b25lQHZzcGhlcmUubG9jYWwiLCJTeXN0ZW1Db25maWd1cmF0aW9uLkFkbWluaXN0cmF0b3JzQHZzcGhlcmUubG9jYWwiXSwiZXhwIjoxNjIzNjk2ODMyLCJpYXQiOjE2MjM2NjA4MzIsImp0aSI6ImVhYmM2ZjhiLWQ2NTYtNDIzYy05ZDBlLTZmMDQ1NzdiNWIzOCIsInVzZXJuYW1lIjoiZGVtbyJ9.QoYiQSBQ8RV5UZWAxD6T69g3gYdtWjSzJYGSpzPs06RW9SRrRxXSQendqySwvJs-xPaduGRQwJh-acoMHV9UpvvWnEvX7kgfZK5tW2doKHzXjwJZnLZRwsTAHx2V9_E0SXW-EA7mjgd4_b1k94_aOPE0cPY9FA5GJoGP8WXT8waXgQ-Q3W1m1hvBe2jt14KQfqLdV1yyvR1CboFIvmH_apISt-1m3iwVlDUgLDnJi2g8mlttKd9D-CRrCWggRDzBLWN42iXrLYIlxm1b1sweXLS76brEA-EvCu_iRkW8j9z364pliPqHwUAx_N-1V_-BryUhc8svctLIFMsLdDH6Dg
