apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.10.30:6443
  name: 10.0.10.30
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.17.0.1:6443
  name: 172.17.0.1
contexts:
- context:
    cluster: 10.0.10.30
    user: wcp:10.0.10.30:demo@vsphere.local
  name: 10.0.10.30
- context:
    cluster: 172.17.0.1
    namespace: demo
    user: wcp:172.17.0.1:demo@vsphere.local
  name: demo
- context:
    cluster: 172.17.0.1
    namespace: demo2
    user: wcp:172.17.0.1:demo@vsphere.local
  name: demo2
current-context: 10.0.10.30
kind: Config
preferences: {}
users:
- name: wcp:10.0.10.30:demo@vsphere.local
  user:
    token: eyJraWQiOiIyMDgxOEMxRTIwNzcwRDY4RDdCMzdDREIxQTRCRjlCNjYxRUFGNjAyIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkZW1vQHZzcGhlcmUubG9jYWwiLCJhdWQiOiJ2bXdhcmUtdGVzOnZjOnZuczprOHMiLCJkb21haW4iOiJ2c3BoZXJlLmxvY2FsIiwiaXNzIjoiaHR0cHM6XC9cLzEwLjAuMTAuMTBcL29wZW5pZGNvbm5lY3RcL3ZzcGhlcmUubG9jYWwiLCJncm91cF9uYW1lcyI6WyJMaWNlbnNlU2VydmljZS5BZG1pbmlzdHJhdG9yc0B2c3BoZXJlLmxvY2FsIiwiQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIkV2ZXJ5b25lQHZzcGhlcmUubG9jYWwiLCJTeXN0ZW1Db25maWd1cmF0aW9uLkFkbWluaXN0cmF0b3JzQHZzcGhlcmUubG9jYWwiXSwiZXhwIjoxNjIzNjk3OTU3LCJpYXQiOjE2MjM2NjE5NTcsImp0aSI6IjA1OWEzZDg3LTFjYzgtNDk3ZC1iYTdhLWE4MmIxODViNDMwNyIsInVzZXJuYW1lIjoiZGVtbyJ9.TBDHubPIh7u7ubx_D2G1gIyytrVBLoqytDi1opxnhaOSromuI6zDxc7JHQEJep-vxIgYMphNjVCXip-BQXyL2J6DbMLp8B7tdoVmWlQ16dAE9mtYljRvJvI_tS3Hnu2WhyELnjZDeyRoQ3uQJEWX5_pQhBw690vt2CJt0YLGM1S8N9TOqP_worK1twd_4-eOVcsDIJX8-vmUUEu-xGPbrnipqe23dN-4Z6mhjCUjHNlmAIW_J34kYmkq3ENv4pPl-isS3rQGAqwmEvBNvLEwxiheTmuByHA0try8pehcnPN0WO9RNKTvP0tgKYy3VF6pDOpcTZw9n_mdgVc5dU5MvQ
- name: wcp:172.17.0.1:demo@vsphere.local
  user:
    token: eyJraWQiOiIyMDgxOEMxRTIwNzcwRDY4RDdCMzdDREIxQTRCRjlCNjYxRUFGNjAyIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkZW1vQHZzcGhlcmUubG9jYWwiLCJhdWQiOiJ2bXdhcmUtdGVzOnZjOnZuczprOHMiLCJkb21haW4iOiJ2c3BoZXJlLmxvY2FsIiwiaXNzIjoiaHR0cHM6XC9cLzEwLjAuMTAuMTBcL29wZW5pZGNvbm5lY3RcL3ZzcGhlcmUubG9jYWwiLCJncm91cF9uYW1lcyI6WyJMaWNlbnNlU2VydmljZS5BZG1pbmlzdHJhdG9yc0B2c3BoZXJlLmxvY2FsIiwiQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIkV2ZXJ5b25lQHZzcGhlcmUubG9jYWwiLCJTeXN0ZW1Db25maWd1cmF0aW9uLkFkbWluaXN0cmF0b3JzQHZzcGhlcmUubG9jYWwiXSwiZXhwIjoxNjIzNjk3OTU5LCJpYXQiOjE2MjM2NjE5NTksImp0aSI6IjE0ZTA1NWI0LTU1ZWItNDdiZi05YThlLWJjYzFmNWFkOGMxOSIsInVzZXJuYW1lIjoiZGVtbyJ9.C5t0R93_pVkc9FPqITPzmalmXVYU_d_DoJvuIZn8AdiMW2EtpXvsKfsjsX8Nv8TfdQEvxBYCWGxP2rI55ROY2MPWNJEyGmyP1X6q2E-N_3wi3AaZggfC0KwJIq0E1tXR1IOpCu6Ajko6uR1qghG4KbCmF_UeJi_8NePDEryV7PdtMGDRNcJn6HDIQ0zxB-wMFwG7-mJONFW3YsjEX_mMBQ3_j7B5FOX-DfC7d-yo8jd1B0tp_Z1DVeZ6yxiu2UgUgKhkGcQgrrui5qeILPYPHIGPM2zBqWTBthbkJtqWYPU4JFTN771LulbNZW01B7c4XsO5c2bhpLakkyNbmH-lBA
