apiVersion: run.tanzu.vmware.com/v1alpha1  #TKGS API endpoint
kind: TanzuKubernetesCluster               #required parameter
metadata:
  name: demo-cluster                       #cluster name, user defined
  namespace: demo                          #vsphere namespace
spec:
  distribution:
    version: v1.20                         #Resolves to latest TKR 1.20 version
  topology:
    controlPlane:
      count: 1                             #number of control plane nodes
      class: best-effort-xsmall            #vmclass for control plane nodes
      storageClass: kubernetes             #storageclass for control plane
    workers:
      count: 2                            #number of worker nodes
      class: best-effort-xsmall            #vmclass for worker nodes
      storageClass: kubernetes              #storageclass for worker nodes
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks: ["10.244.8.0/21"]    # Cannot overlap with Supervisor Cluster
      services:
        cidrBlocks: ["10.97.0.0/24"] # Cannot overlap with Supervisor Cluster
    storage:
      classes: ["kubernetes"]           # Named PVC storage classes
      defaultClass: kubernetes          # Default PVC storage class
